### ISSUE TITLE
Не загружается js

### ISSUE THREAD

**Issue by Vovkt** [silentsokolov/django-treasuremap#2]
Файлы:
https://github.com/silentsokolov/django-treasuremap/blob/master/treasuremap/backends/yandex.py
https://github.com/silentsokolov/django-treasuremap/blob/master/treasuremap/backends/google.py

Ошибка:
'module' object has no attribute 'urlencode'

Причина:
urllib has been split up in Python 3. The urllib.urlencode() function is now urllib.parse.urlencode(), and the urllib.urlopen() function is now urllib.request.urlopen()

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode

**Comment by silentsokolov** [comment]
Fixed, please install new version (0.2.2)

Thx
