### ISSUE TITLE
How can I get latitude and longitude data separately from LatLongField in django model?

### ISSUE THREAD

**Issue by unicornlox** [silentsokolov/django-treasuremap#4]
Hi Sokolov;
How can I get latitude and longitude data separately from LatLongField in django model?
example my models:

```
from django.db import models
from treasuremap.fields import LatLongField
from django.contrib.auth.models import User

class ShopModel(models.Model):
    name = models.CharField(max_length=100)
    point = LatLongField(blank=True)
    user = models.OneToOneField (User)
```
How should I query my database?something like this is possible;

```
latitude = ShopModel.objects.filter(user = request.user, point.latitude = mylatitude)
longitude = ShopModel.objects.filter(user = request.user, point.longitude = mylongitude)
```

**Comment by silentsokolov** [comment]
Use [raw query](https://docs.djangoproject.com/en/1.11/topics/db/sql/) or [custom where](https://docs.djangoproject.com/en/1.11/howto/custom-lookups/), like:
```sql
--- point field: 'latitude;longitude'
SELECT * FROM table1 WHERE split_part(table1.point, ';', 2)::float >= 1
```

But for geometry, I recommend to use [PostGIS](https://docs.djangoproject.com/en/1.11/ref/contrib/gis/install/postgis/)
