### ISSUE TITLE
Typos in README.rst and yandex.py

### ISSUE THREAD

**Issue by jkandrashina** [silentsokolov/django-treasuremap#7]
Hello.
I found several typos in following files:
1. README.rst
[https://github.com/silentsokolov/django-treasuremap/tree/master#in-admin](https://github.com/silentsokolov/django-treasuremap/tree/master#in-admin)
```
from treasuremap.widgets import AdminMapWidget
...
@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    def formfield_for_dbfield(self, db_field, **kwargs):
        if db_field.name == 'point':
            kwargs['widget'] = widgets.AdminMapWidget()
```
Since we imported **AdminMapWidget** directly, the last line should be:

```
kwargs['widget'] = AdminMapWidget()
```

2. yandex.py
[https://github.com/silentsokolov/django-treasuremap/blob/master/treasuremap/backends/yandex.py](https://github.com/silentsokolov/django-treasuremap/blob/master/treasuremap/backends/yandex.py)

```
class YandexMapBackend(BaseMapBackend):
   ...
    def get_api_js(self):
        params = OrderedDict()
        params["lang"] = settings.LANGUAGE_CODE

        if self.API_KEY:
            params["pikey"] = self.API_KEY
```
There is a typo in the name of the dictionary key.
The last line should be:

```
params["apikey"] = self.API_KEY
```

Thanks for the package. It was my first time working with Yandex maps and spatial data. Your package helped me a lot.

**Comment by silentsokolov** [comment]
Thx!
